### PR TITLE
drop support for 0.3

### PR DESCRIPTION
**Pull request by mlubin**

### CODE REVIEW

**Comment by tkelman** [comment]
You haven't tagged this yet have you? Is it maybe the right time to change around the dependencies in the right direction between Cbc and Clp? Could possibly use the Homebrew formulas from https://github.com/coin-or-tools/homebrew-coinor

**Comment by mlubin** [comment]
Not tagged yet. Switching the dependency order is fine with me

**Comment by tkelman** [comment]
It looks like the answer is yes, but double-checking: does clp have its own c api if you build just libclp without cbc?

**Comment by mlubin** [comment]
@tkelman, yes it does.

**Pull request merged**
