### PR TITLE
A thorough modernization of the MOI wrapper

### LINKED ISSUE #79: How to set options with JuMP v0.19.x
Hi there,

With JuMP v0.18.x and below I can set Cbc options with:
```julia
CbcSolver(seconds=5.0)
```

With JuMP v0.19 (alpha) I try the following and get a method error:
```julia
CbcOptimizer(seconds=5.0)
```
How do I set options with the `MathOptInterface`?

### LINKED ISSUE #96: does not support an objective function of type MathOptInterface.SingleVariable.
```julia
using JuMP, Cbc
m = Model(with_optimizer(Cbc.Optimizer))
@variable(m, x1>=0)
@objective(m, Min, x1)
optimize!(m)
```

produces

```
ERROR: The solver does not support an objective function of type MathOptInterface.SingleVariable.
Stacktrace:
 [1] error(::String, ::Type, ::String) at ./error.jl:42
 [2] set_objective_function(::Model, ::MathOptInterface.SingleVariable) at /Users/chkwon/.julia/packages/JuMP/xQHBA/src/objective.jl:63
 [3] set_objective_function at /Users/chkwon/.julia/packages/JuMP/xQHBA/src/objective.jl:73 [inlined]
 [4] set_objective(::Model, ::MathOptInterface.OptimizationSense, ::VariableRef) at /Users/chkwon/.julia/packages/JuMP/xQHBA/src/objective.jl:79
 [5] top-level scope at /Users/chkwon/.julia/packages/JuMP/xQHBA/src/macros.jl:914
```

### LINKED ISSUE #102: MOI is slow querying solution information
As reported by @ndinsmore in https://github.com/JuliaOpt/JuMP.jl/issues/1826, CBC is very slow querying the primal solution:

```julia
using JuMP, Gurobi, Cbc, BenchmarkTools

function bench(optimizer, N = 30_000)
    model = Model(with_optimizer(optimizer))
    @variable(model, x[i = 1:N] >= i)
    @objective(model, Min, sum(x))
    optimize!(model)
    @benchmark value.($x)
end

bench(Cbc.Optimizer)

BenchmarkTools.Trial:
  memory estimate:  6.72 GiB
  allocs estimate:  509495
  --------------
  minimum time:     4.588 s (21.42% GC)
  median time:      4.725 s (21.20% GC)
  mean time:        4.725 s (21.20% GC)
  maximum time:     4.862 s (20.98% GC)
  --------------
  samples:          2
  evals/sample:     1

bench(Gurobi.Optimizer)

BenchmarkTools.Trial:
  memory estimate:  6.63 MiB
  allocs estimate:  389495
  --------------
  minimum time:     42.074 ms (0.00% GC)
  median time:      45.858 ms (0.00% GC)
  mean time:        48.416 ms (4.13% GC)
  maximum time:     82.425 ms (0.00% GC)
  --------------
  samples:          104
  evals/sample:     1
```

Culprit is
https://github.com/JuliaOpt/Cbc.jl/blob/489db0680e71c6ce4f61b991afb1241864923d24/src/MOI_wrapper.jl#L347-L352

### LINKED ISSUE #106: Tests are failing
https://travis-ci.org/JuliaOpt/Cbc.jl/jobs/490566196#L706

Likely due to the MOI 0.8.2 tag.

### PR DESCRIPTION
**Pull request by odow**
This PR closes *all* outstanding MOI related issues and gets Cbc in a nice shape for JuMP 0.19 release.

It was easier to just tidy up the wrapper in one shot that have many PRs sitting in CI.

Closes #107 
Closes #106
Closes #104 
<s>Closes #102</s>
Closes #96
Closes #81
Closes #79

### CODE REVIEW

**Comment by mlubin** [comment]
Note the failure on 0.7 (it's ok to drop 0.7).

**Comment by mlubin** [comment]
I didn't review in too much detail but it's hard to argue with the list of closed issues :). LGTM.
Isn't issue #102 already fixed by #105? 

CC @vitornesello

**Comment by odow** [comment]
The diff is hard to review in detail, but there were lots of bugs/unimplemented features like constants in the objective function. If this passes CI then it is passing every relevant MILP test in MOI so that seems pretty safe... Yay for a strong battery of tests.

**Comment by odow** [comment]
I'll leave dropping 0.7 for another PR.

**Comment by mlubin** [comment]
Tagged a new release as well.

**Comment by vitornesello** [comment]
Thanks guys, I took my time to read the code and indeed the code is better now.
Sorry for the absence lately. I have updated my notifications settings to not miss the messages mentioning me.

**Comment by odow** [comment]
@vitornesello no worries! Thanks for already completing the bulk of the work!

**Pull request merged**
