### PR TITLE
Implement getobjgap

### PR DESCRIPTION
**Pull request by abelsiqueira**
Implement getobjgap acording to the [mathprogbase docs](http://mathprogbasejl.readthedocs.org/en/latest/lowlevel.html#getobjgap). Should there be a check for almost zero?

### CODE REVIEW

**Comment by mlubin** [comment]
I'm not sure if there's any well-defined behavior for the gap if the objective value is zero. Do you know what other solvers do?

**Comment by IainNZ** [comment]
In my own little solver experiments I defined it to be

```
lower_bound == 0.0 && return Inf  # Undefined
lower_bound == Inf && return Inf  # No solves yet
upper_bound == Inf && return Inf  # No incumbent
abs(upper_bound-lower_bound)/abs(lower_bound)
```

**Comment by mlubin** [comment]
It seems like the default floating point rules give reasonable results here?

**Comment by joehuchette** [comment]
This comment is somewhat independent of this PR, but should we be adding these methods to the MathProgBase functions, eg ``MathProgBase.getobjgap``?

**Comment by mlubin** [comment]
We could implement a generic fallback, though it could be confusing if the fallback doesn't give exactly the same value as what, e.g, gurobi would report through the MIPGap attribute (http://www.gurobi.com/documentation/6.0/refman/mipgap.html).

**Pull request merged**
