### PR TITLE
Fix build.jl depwarns

### PR DESCRIPTION
**Pull request by ranjanan**
Fixes OS macro depwarns.

### CODE REVIEW

**Comment by ranjanan** [comment]
I guess since the master branch is failing, there is more work needed to fix the package and then the dep warns.

**Comment by mlubin** [comment]
That was just a hiccup, tests passing now.

**Comment by ranjanan** [comment]
Cool! I hate to be a bother once more, but would you mind tagging a new release please?

**Comment by mlubin** [comment]
@ranjanan: https://github.com/JuliaLang/METADATA.jl/pull/5873

**Comment by ranjanan** [comment]
Thanks!

**Pull request merged**
